### ISSUE TITLE
Please make this a legitimate issue...

### ISSUE THREAD

**Issue by freeslugs** [wsjigga/movie-app#3]

**Comment by wsjigga** [comment]
let's keep this professional as fuck bro. i wanted to change the issues to the format described [here](http://chris.beams.io/posts/git-commit/). read and delete this issue asap. much love :)

**Comment by anishking1** [comment]
Also, don't post anything here that looks dumb to the general public. Like a whaleface. Its not professional..anyway. I'll build my other app later. for now I guess let's build the movie-app as the title suggests.
